use_frameworks!

platform :ios, '13.0'

target 'EAP8021XClient_Example' do
  pod 'EAP8021XClient', :path => '../../'

  target 'EAP8021XClient_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
